# Generated by Django 5.1.4 on 2025-01-22 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_role_ispublisher_role_isreviewer_role_permissions'),
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='header',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='story',
            name='line_up',
        ),
        migrations.RemoveField(
            model_name='story',
            name='sub_header',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_created', to='Authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_updated', to='Authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='story',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_created', to='Authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='story',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_updated', to='Authentication.userprofile'),
        ),
    ]
