# Generated by Django 5.1.4 on 2025-01-22 10:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_rename_ispublisher_role_is_publisher_and_more'),
        ('Core', '0002_rename_header_story_title_remove_story_line_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_content_created', to='Authentication.userprofile')),
                ('story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_id', to='Core.story')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_content_updated', to='Authentication.userprofile')),
            ],
        ),
    ]
