# Generated by Django 5.1.4 on 2025-01-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_url',
            field=models.CharField(max_length=255),
        ),
    ]
