# Generated by Django 5.1.4 on 2025-01-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_role_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recent_stories',
            field=models.JSONField(default=list),
        ),
    ]
