# Generated by Django 5.1.4 on 2025-01-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_userprofile_recent_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='isPublisher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='isReviewer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.JSONField(default=list),
        ),
    ]
