# Generated by Django 5.1.4 on 2025-01-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_role_ispublisher_role_isreviewer_role_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='isPublisher',
            new_name='is_publisher',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='isReviewer',
            new_name='is_reviewer',
        ),
    ]
