# Generated by Django 5.1.4 on 2025-01-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_agreemnet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agreemnet',
            new_name='Agreement',
        ),
    ]
