# Generated by Django 5.1.4 on 2025-01-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_rename_agreemnet_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='name',
            field=models.CharField(default='Default Agreement Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
